version: '3'


services:
  rabbitmq:
    image: 'rabbitmq:3.10.7-management'
    # Прокидываем на localhost порты
    ports:
      # Порт для взаимодействия RabbitMQ сервисов
      - '5672:5672'   # The standard AMQP protocol port
      # Порт для WebGUI настройки
      - '15672:15672' # HTTP management UI
    networks:
      - demo

  consumer:
    # Папка из которой собираем
    build: consumer
    environment:
      # URL для подключения
      AMQP_URL: 'amqp://guest:guest@rabbitmq?connection_attempts=5&retry_delay=5'
    networks:
      - demo

  publisher:
    build: publisher
    environment:
      AMQP_URL: 'amqp://guest:guest@rabbitmq?connection_attempts=5&retry_delay=5'
    networks:
      - demo

networks:
  demo: {}
