apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  labels:
    app: consumer
spec:
  replicas: 1
  template:
    metadata:
      name: consumer
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image:  consumer-image:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: amqphost
              # Amqp host is your rabbitmq cluster service name on Kubernetes
              value: 'rabbitmq-ha'
            - name: queue
              value: 'amqpQueue'
            - name: exchange
              value: 'amq.topic'
            - name: routingkey
              value: 'emre'
      restartPolicy: Always
  selector:
    matchLabels:
      app: consumer
