apiVersion: v1

kind: Service
metadata:
    name: message-handler-service
spec:
    selector:
        app: message-handler-id-name
        tier: backend
    ports:
    - port: 80
      targetPort: http

